<template>
  <div>
    <h2></h2>
  </div>
</template>

<script setup>
const weapons = [
  { name: 'Greataxe', image: '/download-removebg-preview(1).png' },
  { name: 'Longsword', image: '/download-removebg-preview.png' },
  { name: 'Scythe', image: 'download-removebg-preview(3).png' },
  { name: 'Mace', image: '/download-removebg-preview(2).png' },
  { name: 'Spear', image: '/images-removebg-preview.png' },
]
</script>
